[tool.poetry]
name = "Flask-AlchemyDumps"
version = "0.0.12"
description = "SQLAlchemy backup/dump tool for Flask"
authors = ["Eduardo Cuducos <cuducos@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/cuducos/alchemydumps"
classifiers = [
    'Development Status :: 3 - Alpha',
    'License :: OSI Approved :: MIT License',
    'Framework :: Flask',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Intended Audience :: Developers',
    'Topic :: Database',
    'Topic :: System :: Archiving :: Backup',
    'Topic :: Utilities'
]
keywords = [
    "backup",
    "sqlalchemy",
    "flask",
    "restore",
    "ftp"
]
exclude = ["tests/"]

[tool.poetry.dependencies]
python = "^3.6"
Flask = ">=1.1.2"
Flask-SQLAlchemy = "^2.4.1"
python-decouple = "^3.3"
SQLAlchemy = "^1.3.16"

[tool.poetry.dev-dependencies]
Black = "^19.10b0"
flake8 = "^3.7.9"
nose = "^1.3.7"
pytest-black = "^0.3.8"
pytest-flake8 = "^1.0.4"
tox = "^3.14.6"

[tool.pytest.ini_options]
flake8-max-line-length = 88
addopts = "--black --flake8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
